### PR TITLE
.coafile: Add CPD and Radon sections

### PR DESCRIPTION
**Pull request by Adrianzatreanu**

### CODE REVIEW

**Comment by sils** [comment]
have you run them locally? CPD isn't runnable on GitMate atm

**Comment by sils** [comment]
https://github.com/coala-analyzer/coala-decorators/pull/14/commits/8f164929e8be4461850334c55e75308e99e3a5a4 is ready

**Comment by Adrianzatreanu** [comment]
ah apparently cpd requires a langauge

**Comment by Adrianzatreanu** [comment]
im grabbing [WARNING][13:24:45] The bear CPDBear does not fulfill all requirements. CPD is missing. Make sure to install it from https://pmd.github.io/

**Comment by sils** [comment]
well... follow the instructions, what should I say...

**Comment by sils** [comment]
also I'd put CPD and Radon in the same section

**Comment by Adrianzatreanu** [comment]
but why would we want it here then if it wont work?

**Comment by sils** [comment]
because it will be at some point and the coafile is not only for gitmate, it's also for being run locally by you :)

**Comment by Adrianzatreanu** [comment]
same section  now ^^

**Comment by sils** [comment]
ack https://github.com/coala-analyzer/coala-decorators/pull/14/commits/3a3060308a3235cd8b8fb3c3d3fe015a431d0670

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
