### PR TITLE
setup.py: Imports version correctly

### PR DESCRIPTION
**Pull request by Adrianzatreanu**

### CODE REVIEW

**Comment by sils** [comment]
ack https://github.com/coala-analyzer/coala-decorators/pull/16/commits/71c6f0ad2fbda6f3395d1326991825e74e432084 despite weird commit message

**Comment by Adrianzatreanu** [comment]
what is weird about the commit message?

**Comment by Adrianzatreanu** [comment]
the version was imported incorrectly before

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Pull request merged**
